// src/components/layout/Footer.tsx
import React from 'react';
import { Leaf, Facebook, Twitter, Instagram } from 'lucide-react';

export const Footer: React.FC = () => {
  const footerSections = [
    {
      title: 'Shop',
      links: [
        { name: 'Men\'s Shoes', href: '#' },
        { name: 'Women\'s Shoes', href: '#' },
        { name: 'Runners', href: '#' },
        { name: 'Loungers', href: '#' },
        { name: 'Slip-Ons', href: '#' },
        { name: 'Hikers', href: '#' }
      ]
    },
    {
      title: 'Company',
      links: [
        { name: 'About Us', href: '#' },
        { name: 'Sustainability', href: '#' },
        { name: 'Careers', href: '#' },
        { name: 'Press', href: '#' },
        { name: 'Investors', href: '#' }
      ]
    },
    {
      title: 'Support',
      links: [
        { name: 'Contact Us', href: '#' },
        { name: 'Size Guide', href: '#' },
        { name: 'Returns', href: '#' },
        { name: 'Shipping', href: '#' },
        { name: 'Care Instructions', href: '#' }
      ]
    },
    {
      title: 'Social Impact',
      links: [
        { name: 'Carbon Neutral', href: '#' },
        { name: 'Material Innovation', href: '#' },
        { name: 'Regenerative Agriculture', href: '#' },
        { name: 'Environmental Fund', href: '#' }
      ]
    }
  ];

  return (
    <footer className="bg-gray-50 border-t border-gray-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-8">
          {/* Brand Section */}
          <div className="lg:col-span-1">
            <div className="flex items-center space-x-2 mb-4">
              <Leaf className="w-8 h-8 text-emerald-600" />
              <span className="text-2xl font-bold text-gray-900">allbirds</span>
            </div>
            <p className="text-gray-600 mb-6 text-sm leading-relaxed">
              Comfortable, sustainable shoes made from innovative natural materials. 
              Better for your feet, better for the planet.
            </p>
            
            {/* Social Links */}
            <div className="flex space-x-4">
              <a href="#" className="text-gray-400 hover:text-emerald-600 transition-colors">
                <Facebook className="w-5 h-5" />
              </a>
              <a href="#" className="text-gray-400 hover:text-emerald-600 transition-colors">
                <Twitter className="w-5 h-5" />
              </a>
              <a href="#" className="text-gray-400 hover:text-emerald-600 transition-colors">
                <Instagram className="w-5 h-5" />
              </a>
            </div>
          </div>

          {/* Footer Links */}
          {footerSections.map((section) => (
            <div key={section.title}>
              <h3 className="font-semibold text-gray-900 mb-4">{section.title}</h3>
              <ul className="space-y-2">
                {section.links.map((link) => (
                  <li key={link.name}>
                    <a
                      href={link.href}
                      className="text-gray-600 hover:text-emerald-600 transition-colors duration-200 text-sm"
                    >
                      {link.name}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        {/* Bottom Section */}
        <div className="mt-12 pt-8 border-t border-gray-200">
          <div className="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
            <div className="flex flex-wrap items-center space-x-6 text-sm text-gray-600">
              <a href="#" className="hover:text-emerald-600 transition-colors">Privacy Policy</a>
              <a href="#" className="hover:text-emerald-600 transition-colors">Terms of Service</a>
              <a href="#" className="hover:text-emerald-600 transition-colors">Accessibility</a>
              <a href="#" className="hover:text-emerald-600 transition-colors">California Privacy Rights</a>
            </div>
            
            <div className="text-sm text-gray-600">
              © 2025 Allbirds, Inc. All rights reserved.
            </div>
          </div>

          {/* Sustainability Badge */}
          <div className="mt-8 flex justify-center">
            <div className="flex items-center space-x-2 px-4 py-2 bg-emerald-50 rounded-full">
              <Leaf className="w-4 h-4 text-emerald-600" />
              <span className="text-sm font-medium text-emerald-800">Certified B Corporation</span>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
};

// components/Footer.vue
<template>
  <footer class="site-footer">
    <div class="footer-container">
      <div class="footer-content">
        <!-- Brand Section -->
        <div class="footer-brand">
          <div class="logo">
            <svg class="logo-icon" viewBox="0 0 24 24" fill="currentColor">
              <path d="M17 8C8 10 5.9 16.17 3.82 21.34l1.06.82C6.16 17.4 9 12.3 17 10.5V8z"/>
            </svg>
            <span class="logo-text">allbirds</span>
          </div>
          
          <p class="brand-description">
            Comfortable, sustainable shoes made from innovative natural materials. 
            Better for your feet, better for the planet.
          </p>
          
          <div class="social-links">
            <a href="#" class="social-link" aria-label="Facebook">
              <svg viewBox="0 0 24 24" fill="currentColor">
                <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
              </svg>
            </a>
            <a href="#" class="social-link" aria-label="Twitter">
              <svg viewBox="0 0 24 24" fill="currentColor">
                <path d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z"/>
              </svg>
            </a>
            <a href="#" class="social-link" aria-label="Instagram">
              <svg viewBox="0 0 24 24" fill="currentColor">
                <path d="M12.017 0C5.396 0 .029 5.367.029 11.987c0 6.62 5.367 11.987 11.988 11.987 6.62 0 11.987-5.367 11.987-11.987C24.014 5.367 18.637.001 12.017.001zM8.449 16.988c-1.297 0-2.448-.611-3.197-1.559-.748-.948-1.197-2.25-1.197-3.654 0-1.404.449-2.706 1.197-3.654.749-.948 1.9-1.559 3.197-1.559s2.448.611 3.197 1.559c.748.948 1.197 2.25 1.197 3.654 0 1.404-.449 2.706-1.197 3.654-.749.948-1.9 1.559-3.197 1.559z"/>
              </svg>
            </a>
          </div>
        </div>

        <!-- Footer Links -->
        <div class="footer-links">
          <div class="link-column">
            <h3 class="column-title">Shop</h3>
            <ul class="link-list">
              <li><a href="#" class="footer-link">Men's Shoes</a></li>
              <li><a href="#" class="footer-link">Women's Shoes</a></li>
              <li><a href="#" class="footer-link">Runners</a></li>
              <li><a href="#" class="footer-link">Loungers</a></li>
              <li><a href="#" class="footer-link">Slip-Ons</a></li>
              <li><a href="#" class="footer-link">Hikers</a></li>
            </ul>
          </div>

          <div class="link-column">
            <h3 class="column-title">Company</h3>
            <ul class="link-list">
              <li><a href="#" class="footer-link">About Us</a></li>
              <li><a href="#" class="footer-link">Sustainability</a></li>
              <li><a href="#" class="footer-link">Careers</a></li>
              <li><a href="#" class="footer-link">Press</a></li>
              <li><a href="#" class="footer-link">Investors</a></li>
            </ul>
          </div>

          <div class="link-column">
            <h3 class="column-title">Support</h3>
            <ul class="link-list">
              <li><a href="#" class="footer-link">Contact Us</a></li>
              <li><a href="#" class="footer-link">Size Guide</a></li>
              <li><a href="#" class="footer-link">Returns</a></li>
              <li><a href="#" class="footer-link">Shipping</a></li>
              <li><a href="#" class="footer-link">Care Instructions</a></li>
            </ul>
          </div>

          <div class="link-column">
            <h3 class="column-title">Social Impact</h3>
            <ul class="link-list">
              <li><a href="#" class="footer-link">Carbon Neutral</a></li>
              <li><a href="#" class="footer-link">Material Innovation</a></li>
              <li><a href="#" class="footer-link">Regenerative Agriculture</a></li>
              <li><a href="#" class="footer-link">Environmental Fund</a></li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Footer Bottom -->
      <div class="footer-bottom">
        <div class="footer-bottom-content">
          <div class="legal-links">
            <a href="#" class="legal-link">Privacy Policy</a>
            <a href="#" class="legal-link">Terms of Service</a>
            <a href="#" class="legal-link">Accessibility</a>
            <a href="#" class="legal-link">California Privacy Rights</a>
          </div>
          
          <div class="copyright">
            © 2025 Allbirds, Inc. All rights reserved.
          </div>
        </div>

        <div class="certification-badge">
          <div class="badge-content">
            <svg class="badge-icon" viewBox="0 0 24 24" fill="currentColor">
              <path d="M17 8C8 10 5.9 16.17 3.82 21.34l1.06.82C6.16 17.4 9 12.3 17 10.5V8z"/>
            </svg>
            <span class="badge-text">Certified B Corporation</span>
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>

<script>
export default {
  name: 'Footer'
}
</script>

<style scoped>
.site-footer {
  background: #F9FAFB;
  border-top: 1px solid #E5E7EB;
}

.footer-container {
  max-width: 1280px;
  margin: 0 auto;
  padding: 4rem 1rem;
}

.footer-content {
  display: grid;
  grid-template-columns: 1fr 3fr;
  gap: 3rem;
  margin-bottom: 3rem;
}

.footer-brand {
  max-width: 20rem;
}

.logo {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 1rem;
}

.logo-icon {
  width: 2rem;
  height: 2rem;
  color: #10B981;
}

.logo-text {
  font-size: 1.5rem;
  font-weight: 700;
  color: #111827;
}

.brand-description {
  color: #6B7280;
  font-size: 0.875rem;
  line-height: 1.6;
  margin-bottom: 1.5rem;
}

.social-links {
  display: flex;
  gap: 1rem;
}

.social-link {
  color: #9CA3AF;
  transition: color 0.2s ease;
}

.social-link:hover {
  color: #10B981;
}

.social-link svg {
  width: 1.25rem;
  height: 1.25rem;
}

.footer-links {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 2rem;
}

.column-title {
  font-size: 1rem;
  font-weight: 600;
  color: #111827;
  margin-bottom: 1rem;
}

.link-list {
  list-style: none;
  padding: 0;
  margin: 0;
}

.link-list li {
  margin-bottom: 0.5rem;
}

.footer-link {
  color: #6B7280;
  font-size: 0.875rem;
  text-decoration: none;
  transition: color 0.2s ease;
}

.footer-link:hover {
  color: #10B981;
}

.footer-bottom {
  border-top: 1px solid #E5E7EB;
  padding-top: 2rem;
}

.footer-bottom-content {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 2rem;
  flex-wrap: wrap;
  gap: 1rem;
}

.legal-links {
  display: flex;
  gap: 1.5rem;
  flex-wrap: wrap;
}

.legal-link {
  color: #6B7280;
  font-size: 0.875rem;
  text-decoration: none;
  transition: color 0.2s ease;
}

.legal-link:hover {
  color: #10B981;
}

.copyright {
  color: #6B7280;
  font-size: 0.875rem;
}

.certification-badge {
  display: flex;
  justify-content: center;
}

.badge-content {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 1rem;
  background: #F0FDF4;
  border-radius: 9999px;
}

.badge-icon {
  width: 1rem;
  height: 1rem;
  color: #10B981;
}

.badge-text {
  font-size: 0.875rem;
  font-weight: 500;
  color: #065F46;
}

/* Responsive Design */
@media (max-width: 1024px) {
  .footer-content {
    grid-template-columns: 1fr;
    gap: 2rem;
  }
  
  .footer-links {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (max-width: 768px) {
  .footer-container {
    padding: 3rem 1rem;
  }
  
  .footer-links {
    grid-template-columns: 1fr;
  }
  
  .footer-bottom-content {
    flex-direction: column;
    text-align: center;
  }
  
  .legal-links {
    justify-content: center;
  }
}
</style>
